version: '3.7'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network
  web:
    image: thr10/koa_server_test:v1.0.1
    depends_on:
      - database
    ports:
      - 9999:3333
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge